#### Numpy

Numpy is a Fundamental library for scientific computing in python. It Provides support for arrays and matrics along with a collectioni of mathematical functions to operate on thes data structures.

By default is not installed so 
1. You can install it using pip on terminal: pip install -r requirements.txt
2. Direct in jupyter notebook: !pip install numpy



In [1]:
!pip install numpy


In [ ]:
import numpy as np 

# Create array using numpy
# create a 1 Dimensional array
arr1 = np.array([1,2,3,4,5])
print("1D array: ", arr1)
print("Type of array:",type(arr1))
print('General its 1D array because otherside there is no value :',arr1.shape)
 
# Reshape the array

arr1.reshape(1,5) # Reshape the array to 1 row and 5 columns



1D array:  [1 2 3 4 5]
Type of array: <class 'numpy.ndarray'>
General its 1D array because otherside there is no value : (5,)


array([[1, 2, 3, 4, 5]])

In [12]:
arr2 = np.array([[1,2,3,4,5]])
print(arr2.shape) # Its a 2D array with 1 row and 5 columns

(1, 5)


In [ ]:
# 2D array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape) # Its a 2D array with 2 row and 5 columns

(2, 5)


In [24]:
print(np.arange(0,10,2).reshape(5,1))# 5x1 array
np.arange(0,10).reshape(2,5)

[[0]
 [2]
 [4]
 [6]
 [8]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("shape:",arr.shape)
print("Number of Dimensions:",arr.ndim)
print("Size of Array:",arr.size)
print("Data type:",arr.dtype)
print("Item size in bytes:",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Number of Dimensions: 2
Size of Array: 6
Data type: int32
Item size in bytes: 4


In [35]:
## Numpy vectorized operations
# Numpy provides a powerful vectorized operations that can be used to perform operations on entire arrays at onc

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

## Element-wise addition
result_add = arr1 + arr2
print(result_add)

# Element-wise substraction
result_sub = arr2 - arr1
print(result_sub)

# Element-wise multiplication
result_mul = arr1 * arr2
print(result_mul)

# Element-wise division
result_div = arr1 / arr2
print(result_div)


[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [39]:
## Universal Function 
arr = np.array([2,3,4,5])
print(np.sum(arr))  # Output: 14
print(np.prod(arr))  # Output: 120
print(np.sqrt(arr))
print(np.sin(arr))
print(np.exp(arr))
print(np.log(arr))


14
120
[1.41421356 1.73205081 2.         2.23606798]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427]
[  7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.69314718 1.09861229 1.38629436 1.60943791]


In [66]:
## Array Sclicing using Numpy

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original array:\n", arr)

print('slicing:\n',arr[1:])

print('First element in slicing:\n',arr[0][0])

print('second element in slicing:\n',arr[0][1])

print('Third element in slicing:\n',arr[0,2])

print('Element in slicing:\n',arr[1:,1:])

## Modify array element

arr[0,0]=100
print(arr)





Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
slicing:
 [[4 5 6]
 [7 8 9]]
First element in slicing:
 1
second element in slicing:
 2
Third element in slicing:
 3
Element in slicing:
 [[5 6]
 [8 9]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [67]:
## Statistical concepts - Normalization
# To Have a mean of 0 and standard deviation of 1, we need to normalize the data.

data = np.array([1, 2, 3, 4, 5])

# Calculate the mean & standard deviation of the data

mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean ) / std_dev
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [68]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean: ", mean)

# Median
median = np.median(data)
print("Median: ", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

# Variance 
variance = np.var(data)
print("Variance:",variance)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance: 8.25


In [72]:
## Logical operation

data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data>5)
print(data[data>5])
print(data[(data >2) & (data < 8)]) # logical AND operation

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[3 4 5 6 7]
